// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS0YDDOr9yjsl2nNWC53aoDIepudncByk',
    appId: '1:279930207347:android:de53203a3e94f0d071fe06',
    messagingSenderId: '279930207347',
    projectId: 'demoflutter-bff5a',
    databaseURL: 'https://demoflutter-bff5a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoflutter-bff5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJIco9FTFiilx7YGh5ZOT0bkZzWdInfk',
    appId: '1:279930207347:ios:69188e99ef50ef2271fe06',
    messagingSenderId: '279930207347',
    projectId: 'demoflutter-bff5a',
    databaseURL: 'https://demoflutter-bff5a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoflutter-bff5a.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );
}
